
DROP DATABASE IF EXISTS usuarios;
CREATE DATABASE usuarios;

CREATE TABLE usuario_tipo (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL
);

INSERT INTO usuario_tipo (nome) VALUES ('Comum');
INSERT INTO usuario_tipo (nome) VALUES ('Especial');

CREATE TABLE usuario (
  id SERIAL PRIMARY KEY, 
  nome VARCHAR(255) NULL,
  cpf VARCHAR(45) NULL,
  email VARCHAR(45) NULL,
  senha VARCHAR(255) NULL,
  usuario_tipo_id INTEGER REFERENCES usuario_tipo (id) 
    ON DELETE SET NULL 
    ON UPDATE CASCADE, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL
);

